### ISSUE TITLE
Receiving this error when running

### ISSUE THREAD

**Issue by matthewboy2000** [Pigpog/vlc-discord-rpc#9] opened 2018-07-28 16:50 UTC
Running...
(node:4556) UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. ([object Object])
    at RP.emit (events.js:186:19)
    at rpc.login.then.catch (I:\Downloads\vlc-discord-rpc-master\vlc-discord-rpc-master\node_modules\discord-rich-presence\index.js:54:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Pigpog** [comment] 2018-07-28 20:00
Duplicate of #8

**Closed by Pigpog** 2018-07-28 20:00 UTC
